import type { MarketZipData, ZipInfo } from "./types";

// Residential ZIP codes Tampa Buys serves across Tampa Bay: Hillsborough, Pinellas, and Pasco counties. Each has the
// mailing city and a common area name. Area names are approximate (ZIP lines don't follow neighborhood lines), and a
// few ZIPs cross county lines; `county` is the primary one. PO-box-only, military, and campus ZIPs are left out.

const z = (city: string, county: string, area = city): ZipInfo => ({ city, area, county });

const zips: Record<string, ZipInfo> = {
  // Hillsborough County
  "33510": z("Brandon", "Hillsborough"),
  "33511": z("Brandon", "Hillsborough"),
  "33527": z("Dover", "Hillsborough"),
  "33534": z("Gibsonton", "Hillsborough"),
  "33547": z("Lithia", "Hillsborough"),
  "33548": z("Lutz", "Hillsborough"),
  "33549": z("Lutz", "Hillsborough"),
  "33556": z("Odessa", "Hillsborough"),
  "33558": z("Lutz", "Hillsborough"),
  "33563": z("Plant City", "Hillsborough"),
  "33565": z("Plant City", "Hillsborough"),
  "33566": z("Plant City", "Hillsborough"),
  "33567": z("Plant City", "Hillsborough"),
  "33569": z("Riverview", "Hillsborough"),
  "33570": z("Ruskin", "Hillsborough"),
  "33572": z("Apollo Beach", "Hillsborough"),
  "33573": z("Sun City Center", "Hillsborough"),
  "33578": z("Riverview", "Hillsborough"),
  "33579": z("Riverview", "Hillsborough"),
  "33584": z("Seffner", "Hillsborough"),
  "33592": z("Thonotosassa", "Hillsborough"),
  "33594": z("Valrico", "Hillsborough"),
  "33596": z("Valrico", "Hillsborough"),
  "33598": z("Wimauma", "Hillsborough"),
  "33602": z("Tampa", "Hillsborough", "Downtown Tampa"),
  "33603": z("Tampa", "Hillsborough", "Seminole Heights"),
  "33604": z("Tampa", "Hillsborough", "Sulphur Springs"),
  "33605": z("Tampa", "Hillsborough", "Ybor City and East Tampa"),
  "33606": z("Tampa", "Hillsborough", "Hyde Park and Davis Islands"),
  "33607": z("Tampa", "Hillsborough", "West Tampa"),
  "33609": z("Tampa", "Hillsborough", "Westshore"),
  "33610": z("Tampa", "Hillsborough", "East Lake-Orient Park"),
  "33611": z("Tampa", "Hillsborough", "Ballast Point"),
  "33612": z("Tampa", "Hillsborough", "University Area"),
  "33613": z("Tampa", "Hillsborough", "North Tampa"),
  "33614": z("Tampa", "Hillsborough", "Egypt Lake-Leto"),
  "33615": z("Tampa", "Hillsborough", "Town 'n' Country"),
  "33616": z("Tampa", "Hillsborough", "Port Tampa"),
  "33617": z("Tampa", "Hillsborough", "Temple Terrace"),
  "33618": z("Tampa", "Hillsborough", "Carrollwood"),
  "33619": z("Tampa", "Hillsborough", "Palm River-Clair Mel"),
  "33624": z("Tampa", "Hillsborough", "Northdale"),
  "33625": z("Tampa", "Hillsborough", "Citrus Park"),
  "33626": z("Tampa", "Hillsborough", "Westchase"),
  "33629": z("Tampa", "Hillsborough", "Palma Ceia and Bayshore"),
  "33634": z("Tampa", "Hillsborough", "Town 'n' Country"),
  "33635": z("Tampa", "Hillsborough", "Town 'n' Country"),
  "33637": z("Tampa", "Hillsborough", "Temple Terrace"),
  "33647": z("Tampa", "Hillsborough", "New Tampa"),

  // Pinellas County
  "33701": z("St. Petersburg", "Pinellas", "Downtown St. Petersburg"),
  "33702": z("St. Petersburg", "Pinellas", "Northeast St. Petersburg"),
  "33703": z("St. Petersburg", "Pinellas", "Snell Isle"),
  "33704": z("St. Petersburg", "Pinellas", "Old Northeast"),
  "33705": z("St. Petersburg", "Pinellas", "Old Southeast"),
  "33706": z("St. Pete Beach", "Pinellas", "St. Pete Beach and Treasure Island"),
  "33707": z("St. Petersburg", "Pinellas", "Gulfport and Pasadena"),
  "33708": z("Madeira Beach", "Pinellas"),
  "33709": z("St. Petersburg", "Pinellas", "Kenneth City"),
  "33710": z("St. Petersburg", "Pinellas", "Tyrone"),
  "33711": z("St. Petersburg", "Pinellas", "Lakewood Estates"),
  "33712": z("St. Petersburg", "Pinellas", "Midtown"),
  "33713": z("St. Petersburg", "Pinellas", "Historic Kenwood"),
  "33714": z("St. Petersburg", "Pinellas", "Lealman"),
  "33715": z("St. Petersburg", "Pinellas", "Tierra Verde"),
  "33716": z("St. Petersburg", "Pinellas", "Gateway"),
  "33755": z("Clearwater", "Pinellas", "Downtown Clearwater"),
  "33756": z("Clearwater", "Pinellas", "South Clearwater and Belleair"),
  "33759": z("Clearwater", "Pinellas"),
  "33760": z("Clearwater", "Pinellas"),
  "33761": z("Clearwater", "Pinellas", "Countryside"),
  "33762": z("Clearwater", "Pinellas", "Feather Sound"),
  "33763": z("Clearwater", "Pinellas"),
  "33764": z("Clearwater", "Pinellas"),
  "33765": z("Clearwater", "Pinellas"),
  "33767": z("Clearwater Beach", "Pinellas"),
  "33770": z("Largo", "Pinellas"),
  "33771": z("Largo", "Pinellas"),
  "33772": z("Seminole", "Pinellas"),
  "33773": z("Largo", "Pinellas"),
  "33774": z("Largo", "Pinellas"),
  "33776": z("Seminole", "Pinellas"),
  "33777": z("Seminole", "Pinellas"),
  "33778": z("Largo", "Pinellas"),
  "33781": z("Pinellas Park", "Pinellas"),
  "33782": z("Pinellas Park", "Pinellas"),
  "33785": z("Indian Rocks Beach", "Pinellas"),
  "33786": z("Belleair Beach", "Pinellas"),
  "34677": z("Oldsmar", "Pinellas"),
  "34683": z("Palm Harbor", "Pinellas"),
  "34684": z("Palm Harbor", "Pinellas"),
  "34685": z("Palm Harbor", "Pinellas"),
  "34688": z("Tarpon Springs", "Pinellas"),
  "34689": z("Tarpon Springs", "Pinellas"),
  "34695": z("Safety Harbor", "Pinellas"),
  "34698": z("Dunedin", "Pinellas"),

  // Pasco County
  "33523": z("Dade City", "Pasco"),
  "33525": z("Dade City", "Pasco"),
  "33540": z("Zephyrhills", "Pasco"),
  "33541": z("Zephyrhills", "Pasco"),
  "33542": z("Zephyrhills", "Pasco"),
  "33543": z("Wesley Chapel", "Pasco"),
  "33544": z("Wesley Chapel", "Pasco"),
  "33545": z("Wesley Chapel", "Pasco"),
  "33559": z("Lutz", "Pasco"),
  "33576": z("San Antonio", "Pasco"),
  "34610": z("Spring Hill", "Pasco", "Shady Hills"),
  "34637": z("Land O' Lakes", "Pasco"),
  "34638": z("Land O' Lakes", "Pasco"),
  "34639": z("Land O' Lakes", "Pasco"),
  "34652": z("New Port Richey", "Pasco"),
  "34653": z("New Port Richey", "Pasco"),
  "34654": z("New Port Richey", "Pasco"),
  "34655": z("New Port Richey", "Pasco", "Trinity"),
  "34667": z("Hudson", "Pasco"),
  "34668": z("Port Richey", "Pasco"),
  "34669": z("Hudson", "Pasco"),
  "34690": z("Holiday", "Pasco"),
  "34691": z("Holiday", "Pasco"),
};

export const tampa: MarketZipData = {
  counties: ["Hillsborough", "Pinellas", "Pasco"],
  zips,
};
